# Composez does not have its own docs site yet.
# These are set to empty strings so offer_url() calls become no-ops.
website = ""
add_all_files = ""
edit_errors = ""
git = ""
enable_playwright = ""
favicon = ""
model_warnings = ""
token_limits = ""
llms = ""
large_repos = ""
git_index_version = ""
install_properly = ""
analytics = ""
release_notes = ""
edit_formats = ""
models_and_keys = ""
